AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Globals:
  Function:
    Timeout: 30
Resources:
  AuthTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: AuthTable
      AttributeDefinitions:
        - AttributeName: mail
          AttributeType: S
      KeySchema:
        - AttributeName: mail
          KeyType: HASH
      ProvisionedThroughput:
        ReadCapacityUnits: 5
        WriteCapacityUnits: 5
  RegisterFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/
      Handler: register.registerlambda
      Runtime: nodejs18.x
      MemorySize: 128
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref AuthTable
      Events:
        ApiEvent:
          Type: Api
          Properties:
            Path: /register
            Method: post
  LoginFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/
      Handler: login.loginlambda
      Runtime: nodejs18.x
      MemorySize: 128
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref AuthTable
      Events:
        ApiEvent:
          Type: Api
          Properties:
            Path: /login
            Method: post
  VerificationFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/
      Handler: verification.verificationlambda
      Runtime: nodejs18.x
      MemorySize: 128
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref AuthTable
      Events:
        ApiEvent:
          Type: Api
          Properties:
            Path: /verification
            Method: get
  allusers:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/
      Handler: hello.allusers
      Runtime: nodejs18.x
      MemorySize: 128
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref AuthTable
      Events:
        ApiEvent:
          Type: Api
          Properties:
            Path: /users
            Method: get

Outputs:
  ApiGatewayEndpoint:
    Description: "API Gateway endpoint URL"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/custom"
