AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Globals:
  Api:
    Cors:
      AllowMethods: "'OPTIONS,GET,POST,PUT,DELETE'"
      AllowHeaders: "'Content-Type,Authorization'"
      AllowOrigin: "'http://127.0.0.1:4200'"
      # AllowOrigin: "'https://lambda-frontend-olive.vercel.app'"
      AllowCredentials: true
  Function:
    Timeout: 30
    Environment:
      Variables: 
        TableName : !Ref AuthTable
        UserDetailsTable: !Ref UserDetailsTable
        ProductsTable : !Ref ProductsTable
        OrdersTable: !Ref OrdersTable
        # API_BASE_URL: !Sub https://${CorsApi}.execute-api.${AWS::Region}.amazonaws.com/Prod
        # API_BASE_URL: 'http://127.0.0.1:3000'
    
Resources:
  #Cors Api
  CorsApi:
    Type: AWS::Serverless::Api
    Properties:
      Name: "CorsApi"
      StageName: "Prod"
      Cors: 
        AllowOrigin: "'http://127.0.0.1:4200'"
        # AllowOrigin: "'https://lambda-frontend-olive.vercel.app'"
        AllowMethods: "'OPTIONS,GET,POST,PUT,DELETE'"
        AllowHeaders: "'Content-Type,Authorization'"
        AllowCredentials: true

  # Modules Layer
  ModulesLayer:
    Type: AWS::Serverless::LayerVersion
    Properties:
      LayerName: sam-layer-dependencies
      Description: layer with some dependencies
      LicenseInfo: 'Available under the MIT license.'
      ContentUri: ./layers
      CompatibleRuntimes:
        - nodejs18.x
    Metadata:
      BuildMethod: nodejs18.x

  # Tables
  AuthTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: "AuthTable"
      AttributeDefinitions:
        - AttributeName: mail
          AttributeType: S
      KeySchema:
        - AttributeName: mail
          KeyType: HASH
      ProvisionedThroughput:
        ReadCapacityUnits: 5
        WriteCapacityUnits: 5
  UserDetailsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: "UserDetailsTable"
      AttributeDefinitions:
        - AttributeName: user_id
          AttributeType: S
      KeySchema:
        - AttributeName: user_id
          KeyType: HASH
      ProvisionedThroughput:
        ReadCapacityUnits: 5
        WriteCapacityUnits: 5
  ProductsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: "ProductsTable"
      AttributeDefinitions:
        - AttributeName: id
          AttributeType: S
      KeySchema:
        - AttributeName: id
          KeyType: HASH
      ProvisionedThroughput:
        ReadCapacityUnits: 5
        WriteCapacityUnits: 5
  OrdersTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: "OrdersTable"
      AttributeDefinitions:
        - AttributeName: order_id
          AttributeType: S
      KeySchema:
        - AttributeName: order_id
          KeyType: HASH
      ProvisionedThroughput:
        ReadCapacityUnits: 5
        WriteCapacityUnits: 5
  
  #Auth Functions
  RegisterFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: functions/Auth
      Handler: register.registerlambda
      Runtime: nodejs18.x
      MemorySize: 128
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref AuthTable
        - DynamoDBCrudPolicy:
            TableName: !Ref UserDetailsTable
      Layers:
        - !Ref ModulesLayer
      Events:
        ApiEvent:
          Type: Api
          Properties:
            RestApiId: !Ref CorsApi
            Path: /register
            Method: post
  LoginFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: functions/Auth
      Handler: login.loginlambda
      Runtime: nodejs18.x
      MemorySize: 128
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref AuthTable
        - DynamoDBCrudPolicy:
            TableName: !Ref UserDetailsTable
      Layers:
        - !Ref ModulesLayer
      Events:
        ApiEvent:
          Type: Api
          Properties:
            RestApiId: !Ref CorsApi
            Path: /login
            Method: post
  VerificationFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: functions/Auth
      Handler: verification.verificationlambda
      Runtime: nodejs18.x
      MemorySize: 128
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref AuthTable
        - DynamoDBCrudPolicy:
            TableName: !Ref UserDetailsTable
      Layers:
        - !Ref ModulesLayer
      Events:
        ApiEvent:
          Type: Api
          Properties:
            RestApiId: !Ref CorsApi
            Path: /verification
            Method: get
  forgetPasswordFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: functions/Auth
      Handler: forgetpassword.forgetpasswordlambda
      Runtime: nodejs18.x
      MemorySize: 128
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref AuthTable
      Layers:
        - !Ref ModulesLayer
      Events:
        ApiEvent:
          Type: Api
          Properties:
            RestApiId: !Ref CorsApi
            Path: /forgetpassword
            Method: post
  LogoutFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: functions/Auth
      Handler: logout.LogoutLambda
      Runtime: nodejs18.x
      MemorySize: 128
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref AuthTable
      Layers:
        - !Ref ModulesLayer
      Events:
        ApiEvent:
          Type: Api
          Properties:
            RestApiId: !Ref CorsApi
            Path: /logout
            Method: get
  
  #User Verification
  userVerificationFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: functions/Verification
      Handler: userVerification.UserVerificationLambda
      Runtime: nodejs18.x
      MemorySize: 128
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref AuthTable
      Layers:
        - !Ref ModulesLayer
      Events:
        ApiEvent:
          Type: Api
          Properties:
            RestApiId: !Ref CorsApi
            Path: /userverification
            Method: get
  
  #Details Functions
  UserDetailsFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: functions/Details
      Handler: userdetails.UserDetails
      Runtime: nodejs18.x
      MemorySize: 128
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref AuthTable
        - DynamoDBCrudPolicy:
            TableName: !Ref UserDetailsTable
      Layers:
        - !Ref ModulesLayer
      Events:
        GetUserDetails:
          Type: Api
          Properties:
            RestApiId: !Ref CorsApi
            Path: /userdetails
            Method: get
  CartFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: functions/Details
      Handler: cart.CartLambda
      Runtime: nodejs18.x
      MemorySize: 128
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref AuthTable
        - DynamoDBCrudPolicy:
            TableName: !Ref UserDetailsTable
      Layers:
        - !Ref ModulesLayer
      Events:
        UpdateCart:
          Type: Api
          Properties:
            RestApiId: !Ref CorsApi
            Path: /cart
            Method: post
        GetCart:
          Type: Api
          Properties:
            RestApiId: !Ref CorsApi
            Path: /cart
            Method: get
  WishlistFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: functions/Details
      Handler: wishlist.WishlistLambda
      Runtime: nodejs18.x
      MemorySize: 128
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref AuthTable
        - DynamoDBCrudPolicy:
            TableName: !Ref UserDetailsTable
      Layers:
        - !Ref ModulesLayer
      Events:
        UpdateCart:
          Type: Api
          Properties:
            RestApiId: !Ref CorsApi
            Path: /wishlist
            Method: post
        GetCart:
          Type: Api
          Properties:
            RestApiId: !Ref CorsApi
            Path: /wishlist
            Method: get
  OrdersFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: functions/Details
      Handler: orders.OrdersLambda
      Runtime: nodejs18.x
      MemorySize: 128
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref AuthTable
        - DynamoDBCrudPolicy:
            TableName: !Ref UserDetailsTable
        - DynamoDBCrudPolicy:
            TableName: !Ref OrdersTable
      Layers:
        - !Ref ModulesLayer
      Events:
        UpdateCart:
          Type: Api
          Properties:
            RestApiId: !Ref CorsApi
            Path: /orders
            Method: post
        GetCart:
          Type: Api
          Properties:
            RestApiId: !Ref CorsApi
            Path: /orders
            Method: get
  AddressFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: functions/Details
      Handler: address.AddressLambda
      Runtime: nodejs18.x
      MemorySize: 128
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref AuthTable
        - DynamoDBCrudPolicy:
            TableName: !Ref UserDetailsTable
      Layers:
        - !Ref ModulesLayer
      Events:
        PostAddressEvent:
          Type: Api
          Properties:
            RestApiId: !Ref CorsApi
            Path: /address
            Method: post
        GetAddressEvent:
          Type: Api
          Properties:
            RestApiId: !Ref CorsApi
            Path: /address
            Method: get

  #Products Functions
  GetAllProductsFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: functions/Products
      Handler: GetProducts.GetProductsLambda
      Runtime: nodejs18.x
      MemorySize: 128
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref ProductsTable
      Layers:
        - !Ref ModulesLayer
      Events:
        GetProducts:
          Type: Api
          Properties:
            RestApiId: !Ref CorsApi
            Path: /products
            Method: get
        GetProduct:
          Type: Api
          Properties:
            RestApiId: !Ref CorsApi
            Path: /products/{id}
            Method: get
  GetProductsForCategoryFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: functions/Products
      Handler: GetProductsForCategory.GetProductsForCategoryLambda
      Runtime: nodejs18.x
      Policies: 
        - DynamoDBCrudPolicy:
            TableName: !Ref ProductsTable
      Layers:
        - !Ref ModulesLayer     
      Events:
        GetProductsForCategory:
          Type: Api
          Properties:
            RestApiId: !Ref CorsApi
            Path: /category/{name}
            Method: get
  CreateProductsFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: functions/Products
      Handler: CreateProducts.CreateProductLambda
      Runtime: nodejs18.x
      MemorySize: 128
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref ProductsTable
        - S3CrudPolicy:
            BucketName: 'learning-commers-products'
      Layers:
        - !Ref ModulesLayer
      Events:
        ApiEvent:
          Type: Api
          Properties:
            RestApiId: !Ref CorsApi
            Path: /create
            Method: post
  
  #All Users UserDetails
  allusers:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: functions/Local
      Handler: hello.allusers
      Runtime: nodejs18.x
      MemorySize: 128
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref AuthTable
      Layers:
        - !Ref ModulesLayer
      Events:
        ApiEvent:
          Type: Api
          Properties:
            RestApiId: !Ref CorsApi
            Path: /users
            Method: get
  allusersdetails:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: functions/Local
      Handler: hello.alluserdetails
      Runtime: nodejs18.x
      MemorySize: 128
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref AuthTable
        - DynamoDBCrudPolicy:
            TableName: !Ref UserDetailsTable
      Layers:
        - !Ref ModulesLayer
      Events:
        ApiEvent:
          Type: Api
          Properties:
            RestApiId: !Ref CorsApi
            Path: /usersdetails
            Method: get
  
  #All Orderts
  AllOrders:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: functions/Details
      Handler: AllOrders.AllOrdersLambda
      Runtime: nodejs18.x
      MemorySize: 128
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref OrdersTable
      Layers:
        - !Ref ModulesLayer
      Events:
        ApiEvent:
          Type: Api
          Properties:
            RestApiId: !Ref CorsApi
            Path: /allorders
            Method: get


  #local Table Creation functions
  createAuthTableFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: functions/Local
      Handler: hello.hellolambda3
      Runtime: nodejs18.x
      MemorySize: 128
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref AuthTable
      Layers:
        - !Ref ModulesLayer
      Events:
        ApiEvent:
          Type: Api
          Properties:
            Path: /createtable
            Method: get
  createUserDetailsTableFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: functions/Local
      Handler: hello.hellolambda4
      Runtime: nodejs18.x
      MemorySize: 128
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref UserDetailsTable
      Layers:
        - !Ref ModulesLayer
      Events:
        ApiEvent:
          Type: Api
          Properties:
            Path: /createuserdetailstable
            Method: get
  createDetailsTableFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: functions/Local
      Handler: hello.hellolambda
      Runtime: nodejs18.x
      MemorySize: 128
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref ProductsTable
      Layers:
        - !Ref ModulesLayer
      Events:
        ApiEvent:
          Type: Api
          Properties:
            Path: /createdetailstable
            Method: get
  createOrdersTableFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: functions/Local
      Handler: hello.hellolambda5
      Runtime: nodejs18.x
      MemorySize: 128
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref OrdersTable
      Layers:
        - !Ref ModulesLayer
      Events:
        ApiEvent:
          Type: Api
          Properties:
            Path: /createorderstable
            Method: get

# Outputs:
#   ApiGatewayEndpoint:
#     Description: "API Gateway endpoint URL"
#     Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/custom"