AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Globals:
  Function:
    Timeout: 30
    Environment:
      Variables: 
        TableName : !Ref AuthTable
    
Resources:
  ModulesLayer:
    Type: AWS::Serverless::LayerVersion
    Properties:
      LayerName: sam-layer-dependencies
      Description: layer with some dependencies
      LicenseInfo: 'Available under the MIT license.'
      ContentUri: ./layers
      CompatibleRuntimes:
        - nodejs18.x
    Metadata:
      BuildMethod: nodejs18.x
  AuthTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: "AuthTable"
      AttributeDefinitions:
        - AttributeName: mail
          AttributeType: S
      KeySchema:
        - AttributeName: mail
          KeyType: HASH
      ProvisionedThroughput:
        ReadCapacityUnits: 5
        WriteCapacityUnits: 5
  RegisterFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: functions
      Handler: register.registerlambda
      Runtime: nodejs18.x
      MemorySize: 128
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref AuthTable
      Layers:
        - !Ref ModulesLayer
      Events:
        ApiEvent:
          Type: Api
          Properties:
            Path: /register
            Method: post
  LoginFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: functions
      Handler: login.loginlambda
      Runtime: nodejs18.x
      MemorySize: 128
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref AuthTable
      Layers:
        - !Ref ModulesLayer
      Events:
        ApiEvent:
          Type: Api
          Properties:
            Path: /login
            Method: post
  VerificationFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: functions
      Handler: verification.verificationlambda
      Runtime: nodejs18.x
      MemorySize: 128
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref AuthTable
      Layers:
        - !Ref ModulesLayer
      Events:
        ApiEvent:
          Type: Api
          Properties:
            Path: /verification
            Method: get
  allusers:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: functions
      Handler: hello.allusers
      Runtime: nodejs18.x
      MemorySize: 128
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref AuthTable
      Layers:
        - !Ref ModulesLayer
      Events:
        ApiEvent:
          Type: Api
          Properties:
            Path: /users
            Method: get
  forgetPasswordFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: functions
      Handler: forgetpassword.forgetpasswordlambda
      Runtime: nodejs18.x
      MemorySize: 128
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref AuthTable
      Layers:
        - !Ref ModulesLayer
      Events:
        ApiEvent:
          Type: Api
          Properties:
            Path: /forgetpassword
            Method: post
  createTable:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: functions
      Handler: hello.hellolambda3
      Runtime: nodejs18.x
      MemorySize: 128
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref AuthTable
      Layers:
        - !Ref ModulesLayer
      Events:
        ApiEvent:
          Type: Api
          Properties:
            Path: /createtable
            Method: get

Outputs:
  ApiGatewayEndpoint:
    Description: "API Gateway endpoint URL"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/custom"
